# Generated by Django 4.0.4 on 2022-05-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='team',
        ),
    ]
