# Generated by Django 4.0.4 on 2022-04-25 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name_plural': 'Task Statuses'},
        ),
        migrations.AlterModelOptions(
            name='taskurgency',
            options={'verbose_name_plural': 'Task Urgencies'},
        ),
        migrations.AddField(
            model_name='report',
            name='time_created',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
