# Generated by Django 4.0.4 on 2022-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='address_desc',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='address_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='address_longitude',
            field=models.FloatField(default=0),
        ),
    ]
