# Generated by Django 4.0.4 on 2022-04-29 08:08

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskstatus_options_alter_taskurgency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=tasks.models.image_path)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.report')),
            ],
        ),
    ]
