# Generated by Django 3.2.8 on 2022-05-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_address_desc_task_address_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Task Services',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='service',
            field=models.ManyToManyField(to='tasks.TaskService'),
        ),
    ]
